
server:
  port: 4000

spring:
  data:
    redis:
      host: 192.168.1.109
      port: 6379
      timeout: 60000
      lettuce:
        pool:
          max-active: 1
          max-idle: 1


integration:
  url-car-search: http://172.17.0.3:8080/vehicle/all